[package]
name = "ipfs_effector"
version = "0.1.2"
edition = "2018"
publish = false

[dependencies]
eyre = { workspace = true }
log = "0.4.20"
marine-rs-sdk = { workspace = true }
ipfs-effector-types = { workspace = true }