total_memory_limit = "Infinity"

[[module]]
name = "ipfs_effector"
load_from = "../../target/wasm32-wasi/release/ipfs_effector.wasm"
logger_enabled = true

[module.wasi.mapped_dirs]
"/tmp/vault" = "./test_artifacts/temp"
[module.mounted_binaries]
ipfs = "/usr/bin/ipfs"
